openctf/models.py
import time
from datetime import datetime
from io import BytesIO
import sys
import json
import requests
from flask import current_app
from flask_sqlalchemy import SQLAlchemy
from passlib.hash import bcrypt
from sqlalchemy.ext.hybrid import hybrid_property

import logging
from openctf.services import cache, login_manager
from openctf.utils import generate_identicon

db = SQLAlchemy()
avatar_filename = json.dumps(["avatar", "png"])


class Config(db.Model):
    __tablename__ = "config"
    cid = db.Column(db.Integer, primary_key=True, index=True)
    key = db.Column(db.Unicode(32), unique=True, index=True)
    value = db.Column(db.Text)

    @classmethod
    def get(cls, key, default=None):
        config = cls.query.filter_by(key=key).first()
        if config is None:
            return default
        return str(config.value)

    @classmethod
    def set(cls, key, value):
        config = cls.query.filter_by(key=key).first()
        if config is None:
            config = Config(key, value)
            db.session.add(config)
        else:
            config.value = value
        db.session.commit()


class Challenge(db.Model):
    __tablename__ = "challenges"
    id = db.Column(db.Integer, index=True, primary_key=True)
    name = db.Column(db.String(32), unique=True, index=True)
    author = db.Column(db.Unicode(32))
    title = db.Column(db.Unicode(64))
    description = db.Column(db.Text)
    hint = db.Column(db.Text)
    category = db.Column(db.Unicode(64))
    value = db.Column(db.Integer)

    grader = db.Column(db.UnicodeText)
    autogen = db.Column(db.Boolean)
    programming = db.Column(db.Boolean)
    threshold = db.Column(db.Integer)
    weightmap = db.Column(db.PickleType)
    bonus = db.Column(db.PickleType)

    solves = db.relationship("Solve", back_populates="challenge", lazy="subquery")


class Solve(db.Model):
    __tablename__ = "solves"
    id = db.Column(db.Integer, index=True, primary_key=True)
    pid = db.Column(db.Integer, db.ForeignKey("challenges.id"), index=True)
    tid = db.Column(db.Integer, db.ForeignKey("teams.id"), index=True)
    uid = db.Column(db.Integer, db.ForeignKey("users.id"), index=True)
    _date = db.Column("date", db.DateTime, default=datetime.utcnow)
    ip = db.Column(db.Integer)
    correct = db.Column(db.Boolean)
    ua = db.Column(db.Text)
    flag = db.Column(db.Text)

    user = db.relationship("User", back_populates="solves", lazy="subquery")
    team = db.relationship("Team", back_populates="solves", lazy="subquery")
    challenge = db.relationship("Challenge", back_populates="solves", lazy="subquery")


class Team(db.Model):
    __tablename__ = "teams"
    id = db.Column(db.Integer, index=True, primary_key=True)
    teamname = db.Column(db.Unicode(32), unique=True, index=True)
    affiliation = db.Column(db.Unicode(48))
    captain = db.Column(db.Integer)
    members = db.relationship("User", back_populates="team")

    solves = db.relationship("Solve", back_populates="team", lazy="subquery")


class User(db.Model):
    __tablename__ = "users"
    id = db.Column(db.Integer, index=True, primary_key=True)
    tid = db.Column(db.Integer, db.ForeignKey("teams.id"))
    name = db.Column(db.Unicode(32))
    username = db.Column(db.String(16), unique=True, index=True)
    email = db.Column(db.String(128), unique=True, index=True)
    _password = db.Column("password", db.String(128))
    admin = db.Column(db.Boolean, default=False)
    level = db.Column(db.Integer)
    _register_time = db.Column("register_time", db.DateTime, default=datetime.utcnow)
    reset_token = db.Column(db.String(32))
    otp_secret = db.Column(db.String(16))
    otp_confirmed = db.Column(db.Boolean, default=False)
    email_token = db.Column(db.String(32))
    email_verified = db.Column(db.Boolean, default=False)
    _avatar = db.Column("avatar", db.String(128))

    team = db.relationship("Team", back_populates="members")
    solves = db.relationship("Solve", back_populates="user", lazy="subquery")

    @property
    def avatar(self):
        if not self._avatar:
            avatar_file = BytesIO()
            avatar = generate_identicon(self.email)
            avatar.save(avatar_file, format="PNG")
            avatar_file.seek(0)
            response = requests.post("{}/save".format(current_app.config["FILESTORE_URL"]), data={"filename": avatar_filename}, files={"file": avatar_file})
            if response.status_code == 200:
                self._avatar = "/static/%s" % response.text
                db.session.add(self)
                db.session.commit()
        return self._avatar

    def check_password(self, password):
        return bcrypt.verify(password, self.password)

    def get_id(self):
        return str(self.id)

    @staticmethod
    @login_manager.user_loader
    def get_by_id(id):
        query_results = User.query.filter_by(id=id)
        return query_results.first()

    @property
    def is_active(self):
        # TODO This will be based off account standing.
        return True

    @property
    def is_authenticated(self):
        return True

    @hybrid_property
    def password(self):
        return self._password

    @password.setter
    def password(self, password):
        self._password = bcrypt.encrypt(password, rounds=10)

    @hybrid_property
    def register_time(self):
        return int(time.mktime(self._register_time.timetuple()))

openctf/__init__.py
import openctf.app
import openctf.config
import openctf.errors
import openctf.models
import openctf.services
import openctf.stats
import openctf.views

openctf/app.py
import os

from flask import Flask


def create_app(debug=False, testing=False):
    app = Flask(__name__)

    with app.app_context():
        if debug:
            app.debug = True
            app.config["DEBUG"] = True
            app.config["TEMPLATES_AUTO_RELOAD"] = True

        from openctf.config import Configuration
        app.config.from_object(Configuration(
            app_root=os.path.dirname(os.path.abspath(__file__)),
            testing=testing))

        from openctf.models import db, Config
        db.init_app(app)

        from openctf.services import cache, celery, login_manager
        cache.init_app(app)
        celery.init_app(app)
        login_manager.init_app(app)

        from openctf import views
        app.register_blueprint(views.base.blueprint)
        app.register_blueprint(views.admin.blueprint, url_prefix="/admin")
        app.register_blueprint(views.users.blueprint, url_prefix="/users")

        from openctf.errors import handle_errors
        handle_errors(app)

        @app.context_processor
        def inject_config():
            config = {
                "ctf_name": Config.get("ctf_name", "OpenCTF")
            }
            return config

        return app

if __name__ == "__main__":
    app = create_app()
    app.run(host="0.0.0.0", port=3000, use_debugger=True, use_reloader=True)

openctf/views/__init__.py
import openctf.views.admin
import openctf.views.base
import openctf.views.users

openctf/views/admin.py
from flask import Blueprint

blueprint = Blueprint("admin", __name__, template_folder="templates")


@blueprint.route("/settings")
def settings():
    return "hi"

openctf/views/base.py
import logging

from flask import Blueprint, redirect, render_template, request, url_for
from flask_login import login_user
from flask_wtf import FlaskForm
from wtforms import ValidationError
from wtforms.fields import (IntegerField, PasswordField, StringField,
                            SubmitField, TextAreaField)
from wtforms.validators import Email, EqualTo, InputRequired, Length, Optional

from openctf.models import Config, db
from openctf.stats import compute_all_scoreboard, compute_ranked_scoreboard
from openctf.utils import VALID_USERNAME, generate_string
from openctf.views.users import register_user

blueprint = Blueprint("base", __name__, template_folder="templates")


@blueprint.route("/")
def index():
    return render_template("base/index.html")


@blueprint.route("/scoreboard")
def scoreboard():
    compute_all_scoreboard.apply_async()
    compute_ranked_scoreboard.apply_async()
    return render_template("base/scoreboard.html")


@blueprint.route("/setup", methods=["GET", "POST"])
def setup():
    if Config.get("setup_complete"):
        abort(404)
    if request.method == "GET":  # Config.get("setup_verification") is None:
        verification_code = generate_string()
        logging.warning("Verification code is: " + verification_code)
        Config.set("setup_verification", verification_code)
    setup_form = SetupForm()
    if setup_form.validate_on_submit():
        for field in setup_form:
            if field.name in ["csrf_token", "submit"]:
                continue
            db.session.add(Config(key=field.name, value=field.data))
        db.session.add(Config(key="setup_complete", value="True"))
        user = register_user(setup_form.name.data, setup_form.email.data, setup_form.username.data,
                             setup_form.password.data, 0, admin=True, send_email=False)
        login_user(user)
        db.session.commit()
        return redirect(url_for("base.index"))
    return render_template("base/setup.html", setup_form=setup_form)


class SetupForm(FlaskForm):
    ctf_name = StringField("CTF Name", validators=[InputRequired("Please enter a CTF name.")])
    ctf_description = TextAreaField("CTF Description", validators=[Optional()])
    start_time = IntegerField("Start Time", validators=[InputRequired("Please enter a CTF start time.")])
    end_time = IntegerField("End Time", validators=[InputRequired("Please enter a CTF end time.")])
    team_size = IntegerField("Team Size", default=5, validators=[InputRequired("Please enter a max team size.")])

    name = StringField("Name", validators=[InputRequired("Please enter a name.")])
    username = StringField("Username", validators=[InputRequired("Please enter a username."), Length(3, 24, "Your username must be between 3 and 24 characters long.")])
    email = StringField("Email", validators=[InputRequired("Please enter an email."), Email("Please enter a valid email.")])
    password = PasswordField("Password", validators=[InputRequired("Please enter a password.")])
    confirm_password = PasswordField("Confirm Password", validators=[InputRequired("Please confirm your password."), EqualTo("password", "Please enter the same password.")])

    verification = StringField("Verification", validators=[InputRequired("Please enter a verification code.")])
    submit = SubmitField("Create CTF")

    def validate_username(self, field):
        if not VALID_USERNAME.match(field.data):
            raise ValidationError("Username must be contain letters, numbers, or _, and not start with a number.")

    def validate_verification(self, field):
        code = Config.get("setup_verification")
        if code is None or code != field.data:
            raise ValidationError("Verification failed.")

openctf/views/users.py
from flask import (Blueprint, abort, current_app, flash, redirect,
                   render_template, request, url_for)
from flask_login import current_user, login_required, login_user, logout_user
from flask_wtf import FlaskForm
from sqlalchemy import func
from wtforms import ValidationError
from wtforms.fields import *
from wtforms.validators import *

from openctf.constants import UserLevel, UserLevelNames
from openctf.models import User, db
from openctf.utils import (VALID_USERNAME, generate_string,
                           get_redirect_target, redirect_back, sendmail)

blueprint = Blueprint("users", __name__, template_folder="templates")


@blueprint.route("/forgot")
def forgot():
    return "hi"


@blueprint.route("/login", methods=["GET", "POST"])
def login():
    if current_user.is_authenticated:
        return redirect(url_for("users.profile"))
    login_form = LoginForm()
    next = get_redirect_target()
    if login_form.validate_on_submit():
        # TODO: make sure user's email is verified!
        login_user(login_form.get_user(), remember=login_form.remember.data)
        return redirect_back("users.profile")
    return render_template("users/login.html", login_form=login_form, next=next)


@blueprint.route("/logout", methods=["GET"])
def logout():
    logout_user()
    return redirect(url_for("base.index"))


@blueprint.route("/profile")
@blueprint.route("/profile/<int:id>")
def profile(id=None):
    if id is None and current_user.is_authenticated:
        return redirect(url_for("users.profile", id=current_user.id))
    user = User.get_by_id(id)
    if user is None:
        abort(404)
    level = user.level
    if not level:
        level = -1
    user.type = UserLevelNames[UserLevel(level)]
    return render_template("users/profile.html", user=user)


@blueprint.route("/register", methods=["GET", "POST"])
def register():
    if current_user.is_authenticated:
        return redirect(url_for("users.profile"))
    register_form = RegisterForm()
    if register_form.validate_on_submit():
        new_user = register_user(register_form.name.data,
                                 register_form.email.data,
                                 register_form.username.data,
                                 register_form.password.data,
                                 int(register_form.level.data), admin=False)
        if current_app.config["EMAIL_VERIFICATION_REQUIRED"]:
            # Make sure they verify their email first.
            flash("You've registered! Check your inbox for a confirmation email.", "success")
            return redirect(url_for("users.login"))
        else:
            # Go ahead and log the user in.
            login_user(new_user)
            return redirect(url_for("users.profile"))
    return render_template("users/register.html", register_form=register_form)


@blueprint.route("/settings")
def settings():
    return render_template("users/settings.html")


@blueprint.route("/verify/<string:code>")
@login_required
def verify(code):
    if current_user.email_verified:
        flash("You've already verified your email.", "info")
    elif current_user.email_token == code:
        current_user.email_verified = True
        db.session.commit()
        flash("Email verified!", "success")
    else:
        flash("Incorrect code.", "danger")
    return redirect(url_for("users.settings"))


def register_user(name, email, username, password, level, admin=False, send_email=True, **kwargs):
    new_user = User(name=name, username=username, password=password, email=email, level=level, admin=admin)
    # TODO limit this to certain values, I forgot what this was for.
    for key, value in kwargs.items():
        setattr(new_user, key, value)
    code = generate_string()
    new_user.email_token = code
    if send_email and current_app.config["MAILGUN_API_KEY"]:
        send_verification_email(username, email, url_for("users.verify", code=code, _external=True))
    db.session.add(new_user)
    db.session.commit()
    return new_user


def send_verification_email(username, email, verification_link):
    ctf_name = Config.get("ctf_name")
    subject = "[ACTION REQUIRED] Email Verification - %s" % ctf_name
    body = string.Template(open("email.txt").read()).substitute({
        "link": verification_link,
        "ctf_name": ctf_name,
        "username": username
    })
    response = sendmail(email, subject, body)


class LoginForm(FlaskForm):
    username = StringField("Username", validators=[InputRequired("Please enter your username.")])
    password = PasswordField("Password", validators=[InputRequired("Please enter your password.")])
    remember = BooleanField("Remember Me")
    submit = SubmitField("Login")

    def get_user(self):
        query = User.query.filter(func.lower(User.username) == self.username.data.lower())
        return query.first()

    def validate_username(self, field):
        if not self.get_user():
            raise ValidationError("This user doesn't exist.")

    def validate_password(self, field):
        user = self.get_user()
        if not user:
            return  # should never happen
        if not user.check_password(field.data):
            raise ValidationError("Check your password again.")


class RegisterForm(FlaskForm):
    name = StringField("Name", validators=[InputRequired("Please enter a name.")])
    username = StringField("Username", validators=[InputRequired("Please enter a username."), Length(3, 24, "Your username must be between 3 and 24 characters long.")])
    email = StringField("Email", validators=[InputRequired("Please enter an email."), Email("Please enter a valid email.")])
    password = PasswordField("Password", validators=[InputRequired("Please enter a password.")])
    confirm_password = PasswordField("Confirm Password", validators=[InputRequired("Please confirm your password."), EqualTo("password", "Please enter the same password.")])
    level = RadioField("Eligibility status:", choices=[("1", "Eligible"), ("2", "Ineligible"), ("3", "Teacher")])
    github_id = HiddenField(validators=[Optional()])
    google_id = HiddenField(validators=[Optional()])
    submit = SubmitField("Register")

    def validate_username(self, field):
        if not VALID_USERNAME.match(field.data):
            raise ValidationError("Username must be contain letters, numbers, or _, and not start with a number.")
        if User.query.filter(func.lower(User.username) == field.data.lower()).count():
            raise ValidationError("Username is taken.")

    def validate_email(self, field):
        if User.query.filter(func.lower(User.email) == field.data.lower()).count():
            raise ValidationError("Email is taken.")

openctf/templates/footer.html
<div class="container">
    <hr />
    <center>
        <p>
            Powered by <a href="https://github.com/easyctf/openctf" target="_blank" rel="noopener">OpenCTF</a>, an open-source CTF platform.
        </p>
    </center>
</div>

openctf/templates/layout.html
<!DOCTYPE html>
<html>

<head>
    <title>
        {% block title %}{% endblock %} - {{ ctf_name }}</title>
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="application-name" content="{{ ctf_name }}" />
    <meta name="msapplication-tooltip" content="{{ ctf_name }}" />
    <meta name="description" content="{{ ctf_description }}" />
    <meta name="og:title" content="{{ self.title() }} - {{ ctf_name }}" />
    <meta name="og:site_name" content="{{ ctf_name }}" />
    <meta name="og:description" content="{{ ctf_description }}" /> {% if keywords %}
    <meta name="keywords" content="{{ keywords }}" />{% endif %}
    <link href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous">
    <link href="https://maxcdn.bootstrapcdn.com/font-awesome/4.6.3/css/font-awesome.min.css" rel="stylesheet" integrity="sha384-T8Gy5hrqNKT+hzMclPo118YTQO6cYprQmhrYwIiQ/3axmI1hQomh7Ud2hPOy8SP1" crossorigin="anonymous">
    <link rel="stylesheet" href="https://rawgit.com/cblweb/semantic-ui-bootstrap/5da87845ae19ff6cb806d40da700a32b0c019f1a/css/smt-bootstrap.css" />
    <script src="https://code.jquery.com/jquery-2.1.4.min.js" integrity="sha384-R4/ztc4ZlRqWjqIuvf6RX5yb/v90qNGx6fS48N0tRxiGkqveZETq72KgDVJCp2TC" crossorigin="anonymous"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js" integrity="sha384-Tc5IQib027qvyjSMfHjOMaLkfuWVxZxUPnCJA7l2mCWNIpG9mGCD8wGNIcPD7Txa" crossorigin="anonymous"></script>
    <script type="text/javascript" src="https://cdnjs.cloudflare.com/ajax/libs/moment.js/2.15.1/moment.min.js" integrity="sha256-4PIvl58L9q7iwjT654TQJM+C/acEyoG738iL8B8nhXg=" crossorigin="anonymous"></script>
    <script type="text/javascript" src="https://cdnjs.cloudflare.com/ajax/libs/livestamp/1.1.2/livestamp.min.js" integrity="sha256-8r65KJgULBDiZhwDydfWrEkx3yyV/grGsGzaekobngI=" crossorigin="anonymous"></script>
</head>

<body>
    {% include "navbar.html" %}

    <div style="min-height:80vh;">
        {% block content %}{% endblock %}
    </div>

    {% include "footer.html" %}
</body>

</html>

openctf/templates/macro.html
{% macro flashes() %}
    {% with messages = get_flashed_messages(with_categories=true) %}
        {% if messages %}
            {% for category, message in messages %}
                <div class="alert alert-{{ category or 'info' }}">
                    {{ message }}
                </div>
            {% endfor %}
        {% endif %}
    {% endwith %}
{% endmacro %}

{% macro show_breadcrumbs(breadcrumbs) %}
    <ol class="breadcrumb container">
        {% for breadcrumb in breadcrumbs %}
            <li{{ ' class = "active"' | safe if loop.last }}><a href="{{ breadcrumb.url }}">{{ breadcrumb.text }}</a></li>
        {% endfor %}
    </ol>
{% endmacro %}

{% macro render_field(field) %}
    <div class="form-group">
        {{ field.label(class_="control-label") }}
        {{ field(class_="form-control", autocomplete="off", **kwargs.get("options", {})) }}
        {% if field.errors %}
            <p style="color: #F00;">
                {% for error in field.errors %}
                    {{ error }}<br/>
                {% endfor %}
            </p>
        {% endif %}
    </div>
{% endmacro %}

{% macro render_generic_field(field) %}
    <div class="form-group">
        {{ field.label(class_="control-label") }}
        {{ field(autocomplete="off") }}
        {% if field.errors %}
            <p style="color: #F00;">
                {% for error in field.errors %}
                    {{ error }}<br/>
                {% endfor %}
            </p>
        {% endif %}
    </div>
{% endmacro %}

{% macro render_editor(field, language) %}
    <div class="form-group">
        {{ field.label(class_="control-label") }}
        {{ field(style="display:none;") }}
        <div id="{{ field.name }}_editor"></div>
        {% if field.errors %}
            <p style="color: #F00;">
                {% for error in field.errors %}
                    {{ error }}<br/>
                {% endfor %}
            </p>
        {% endif %}
    </div>
    <script type="text/javascript">
        $(document).ready(function () {
            var {{ field.name }} = ace.edit("{{ field.name }}_editor");
            {{ field.name }}.setTheme("ace/theme/tomorrow");
            {{ field.name }}.getSession().setMode("ace/mode/{{ language }}");
            {{ field.name }}.setValue(`{{ "" if not field.data else field.data.replace("`", "\\`").replace("$", "\\$") | safe }}`);
            {{ field.name }}.on("change", function () {
                $("textarea[name={{ field.name }}]").val({{ field.name }}.getValue());
            });
        });
    </script>
{% endmacro %}

openctf/templates/navbar.html
<nav role="navigation" class="navbar navbar-inverse" id="navbar">
    <div class="container">
        <div class="navbar-header">
            <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar-content" aria-expanded="false">
            <span class="sr-only">Toggle navigation</span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
        </button>
            <a class="navbar-brand" href="{{ url_for('base.index') }}">OpenCTF</a>
        </div>
        <div id="navbar-content" class="collapse navbar-collapse">
            <ul class="nav navbar-nav">
                <li><a href="{{ url_for('base.scoreboard') }}">Scoreboard</a></li>
            </ul>
            <ul class="nav navbar-nav navbar-right">
                {% if current_user.is_authenticated %}
                    {% if current_user.admin %}
                        <li class="dropdown">
                            <a href="javascript:void(0);" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-expanded="false">Admin<span class="caret"></span></a>
                            <ul class="dropdown-menu" role="menu">
                                <li><a href="{{ url_for('admin.settings') }}">CTF Settings</a></li>
                            </ul>
                        </li>
                    {% endif %}
                    <li class="dropdown">
                        <a href="javascript:void(0);" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-expanded="false">
                            {{ current_user.username }}<span class="caret"></span></a>
                        <ul class="dropdown-menu" role="menu">
                            <li><a href="{{ url_for('users.profile') }}">My Profile</a></li>
                            <li role="separator" class="divider"></li>
                            <li><a href="{{ url_for('users.settings') }}">Settings</a></li>
                            <li><a href="{{ url_for('users.logout') }}">Logout</a></li>
                        </ul>
                    </li>
                {% else %}
                    <li><a href="{{ url_for('users.register') }}">Register</a></li>
                    <li><a href="{{ url_for('users.login') }}">Login</a></li>
                {% endif %}
            </ul>
        </div>
    </div>
</nav>